version: '2'
services:
  go-cve-dictionary:
    build:
      context: ..
      dockerfile: ./docker/go-cve-dictionary/Dockerfile
    image: go-cve-dictionary
    links:
      - "database"
    volumes:
      - ./cve-data/:/vuls
      - ./cve-data/logs:/var/log/vuls
    depends_on:
      - database
